# Generated by Django 2.2.3 on 2019-10-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Residence', '0007_reponsesondage_nombrevote'),
        ('Habitant', '0003_auto_20191012_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profil'),
        ),
        migrations.CreateModel(
            name='cotisationValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residence.sondage')),
            ],
        ),
    ]
