# Generated by Django 2.2.3 on 2019-10-31 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Habitant', '0004_auto_20191012_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profil'),
        ),
    ]
