# Generated by Django 2.2.3 on 2019-11-01 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Habitant', '0005_auto_20191031_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotisationvalidation',
            name='sondage',
        ),
        migrations.AddField(
            model_name='cotisationvalidation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
