# Generated by Django 2.2.3 on 2019-11-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20191010_2310'),
        ('Habitant', '0007_auto_20191101_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisationvalidation',
            name='batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Batiment'),
            preserve_default=False,
        ),
    ]
