# Generated by Django 2.2.3 on 2019-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitant', '0008_cotisationvalidation_batiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisationvalidation',
            name='reponse',
            field=models.BooleanField(default=False),
        ),
    ]
