# Generated by Django 2.2.3 on 2019-09-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etage', models.IntegerField()),
                ('nombreHabitant', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='newAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero', models.CharField(max_length=13)),
                ('typeClient', models.CharField(max_length=2)),
                ('ville', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('quartier', models.CharField(max_length=10)),
                ('etat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MA', 'Manager'), ('CM', 'Commercial'), ('VA', 'Validateur'), ('HP', 'Habitant Permanent'), ('HL', 'Habitant Locataire'), ('SY', 'Syndique'), ('NV', 'Nouveau Habitant')], default='HP', max_length=2)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('appartement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Appartement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nbrApp', models.IntegerField()),
                ('nbrResidant', models.IntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Batiment'),
        ),
    ]
