# Generated by Django 2.2.3 on 2019-10-10 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='appartement',
        ),
        migrations.AddField(
            model_name='profil',
            name='batiment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Batiment'),
        ),
    ]
