# Generated by Django 2.2.3 on 2019-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20191010_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newacc',
            name='typeClient',
            field=models.CharField(choices=[('MA', 'Manager'), ('CM', 'Commercial'), ('VA', 'Validateur'), ('HP', 'Habitant Permanent'), ('HL', 'Habitant Locataire'), ('SY', 'Syndique'), ('NV', 'Nouveau Habitant')], max_length=2),
        ),
    ]
