# Generated by Django 2.2.3 on 2019-11-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20191102_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='appartement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Appartement'),
        ),
    ]
