# Generated by Django 2.2.3 on 2019-11-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20191103_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='appartement',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Appartement'),
        ),
    ]
