# Generated by Django 2.2.3 on 2019-09-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Syndics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentBatiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='documentBatiment/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Batiment')),
            ],
        ),
    ]
