# Generated by Django 2.2.3 on 2019-09-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sondage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('finSondage', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Batiment')),
            ],
        ),
        migrations.CreateModel(
            name='reponseSondage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.CharField(max_length=30)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residence.sondage')),
            ],
        ),
    ]
