# Generated by Django 2.2.3 on 2019-10-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Residence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prix', models.IntegerField()),
                ('habitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='alerte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField(default=False)),
                ('vue', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='image_alerte')),
                ('habitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profil')),
            ],
        ),
    ]
