# Generated by Django 2.2.3 on 2019-10-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Residence', '0002_alerte_cotisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Batiment'),
            preserve_default=False,
        ),
    ]
