# Generated by Django 2.2.3 on 2019-10-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20191010_2310'),
        ('Residence', '0003_alerte_batiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='assemblee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type_ass', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Batiment')),
            ],
        ),
    ]
