# Generated by Django 2.2.3 on 2019-10-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residence', '0004_assemblee'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblee',
            name='titre',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
