# Generated by Django 2.2.3 on 2019-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residence', '0005_assemblee_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblee',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
