# Generated by Django 2.2.3 on 2019-10-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residence', '0006_assemblee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponsesondage',
            name='nombreVote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
