# Generated by Django 2.2.3 on 2019-10-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residence', '0007_reponsesondage_nombrevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblee',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
