# Generated by Django 2.2.3 on 2019-10-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Residence', '0008_auto_20191013_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordreAssemblee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residence.assemblee')),
            ],
        ),
    ]
