# Generated by Django 2.2.3 on 2019-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residence', '0009_ordreassemblee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponsesondage',
            name='nombreVote',
            field=models.IntegerField(default=0),
        ),
    ]
