# Generated by Django 2.2.3 on 2019-10-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residence', '0011_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(max_length=2),
            preserve_default=False,
        ),
    ]
