# Generated by Django 2.2.3 on 2019-11-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20191010_2310'),
        ('Residence', '0012_evenement_type_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Batiment'),
            preserve_default=False,
        ),
    ]
